language: python
python:
  - "2.7"
install:
  # Turn on virtual framebuffer so GUI programs like Firefox can be launched
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Buildout needs new setuptools merged with Distribute
  - pip install --upgrade setuptools
  
  # Get buildout
  - python bootstrap.py
  
  # Setup project
  - bin/buildout
script:
  - bin/long-check
